### ISSUE TITLE
Issue with python parser of bdl.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#91]

**Comment by loguntsov** [comment]
I have this mistake:

```
Traceback (most recent call last):
  File "./lib/mzbench/bin/mzbench", line 674, in <module>
    main()
  File "./lib/mzbench/bin/mzbench", line 657, in main
    return apply_args(globals()[cmd], args)
  File "./lib/mzbench/bin/mzbench", line 645, in apply_args
    return fun(**dict((k, get_arg(k, kwargs)) for k in argnames))
  File "./lib/mzbench/bin/mzbench", line 292, in run
    exclusive_node_usage, name, cloud, tags, env, no_cert_check = no_cert_check)
  File "./lib/mzbench/bin/mzbench", line 316, in start
    no_cert_check=no_cert_check)
  File "/home/begemot/erl/oncam/load_test/mzbench_oncam/lib/mzbench/bin/../lib/mzbench_api_client.py", line 65, in start
    script_terms = script_utils.convert(script_content, env)
  File "/home/begemot/erl/oncam/load_test/mzbench_oncam/lib/mzbench/bin/../lib/bdl_utils.py", line 12, in convert
    ast = transform(lex(contents))
  File "/home/begemot/erl/oncam/load_test/mzbench_oncam/lib/mzbench/bin/../lib/bdl_utils.py", line 165, in lex
    return grammar.parse(add_indents(text))
  File "/home/begemot/erl/oncam/load_test/mzbench_oncam/lib/mzbench/bin/../lib/bdl_utils.py", line 54, in add_indents
    comma = tline[0]
IndexError: string index out of range
make: *** [run] Ошибка 1
```
i debugged this code, and found that it depends from this code:

```
make_install(
  git = "URL",
  branch = "master",
  dir = "."
)
```

and this script works fine when i uses run_local command for mzbench.
So i debugged this code, and made changes in script:

```
make_install(
  git = "URL",
  branch = "master",
  dir = ".")
```

At this works fine.
So i have make conclusion that it is parse/lexer issue for python.
Pls fix mistake.

P.S. May you will makes bison/yecc like file to have parser/lexer for erlang/python ?

**Comment by loguntsov** [comment]
Up.

**Comment by parsifal-47** [comment]
fixed,
we already use PEG for parser generation both in Erlang and Python:
https://github.com/machinezone/mzbench/blob/master/lib/bdl_utils.py#L147

but grammars are not completely the same because PEG-parsers are specific to language, bison/yacc are more low-level compared to PEG
